### ISSUE TITLE
OCLP display unsupported host OS

### ISSUE THREAD

**Issue by txl263** [perez987/macOS-15-Sequoia-on-z390-with-OpenCore#1] opened 2024-07-30 14:30 UTC
Hi
I can't find AMFIPass version 1.4.1  and OCLP display unsupported host OS
OS : macOS 15.0 24A5298h x86_64

![截屏2024-07-30 22 28 15](https://github.com/user-attachments/assets/35fc3371-106c-4a12-9d30-9da29d28df19)

**Comment by perez987** [comment] 2024-07-30 16:24
@txl263 
AMFIPass.kext 1.4.1 is inside OCLP package, go to `OpenCore-Legacy-Patcher/payloads/Kexts/Acidanthera/`.
[Link](https://github.com/dortania/OpenCore-Legacy-Patcher/tree/sequoia-development/payloads/Kexts/Acidanthera)

`Unsupported Host OS` is an issue that some users are having on macOS 15 beta when trying to use OCLP. The cause is unclear.
Sometimes it is fixed by going into OCLP Settings >> change Target Model from Host Model to one of the SMBIOS listed, even if it doesn't match yours, then close Settings >> Post Install Root Patch again.

![oclp](https://github.com/user-attachments/assets/4ee29be5-9a78-4319-9ffb-2a87b3753001)

**Comment by txl263** [comment] 2024-08-01 10:02
> @txl263 AMFIPass.kext 1.4.1 is inside OCLP package, go to `OpenCore-Legacy-Patcher/payloads/Kexts/Acidanthera/`. 
> 
> `Unsupported Host OS` is an issue that some users are having on macOS 15 beta when trying to use OCLP. The cause is unclear. Sometimes it is fixed by going into OCLP Settings >> change Target Model from Host Model to one of the SMBIOS listed, even if it doesn't match yours, then close Settings >> Post Install Root Patch again.

I have checked the poison `OpenCore-Legacy-Patcher/payloads/Kexts/Acidanthera/`, there is only 
  [AMFIPass-v1.4.0-RELEASE.zip ](https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/payloads/Kexts/Acidanthera/AMFIPass-v1.4.0-RELEASE.zip)  in it.
And tried several Target Model but no-one can be used. But thank you.

**Comment by txl263** [comment] 2024-08-01 10:13
https://github.com/dortania/OpenCore-Legacy-Patcher/actions/runs/10097655313 This version is OK.

**Comment by perez987** [comment] 2024-08-01 18:10
@txl263 
Sorry, the link was pointing to the main branch and not to the sequoia-development branch.
This is okay too:
[Link](https://github.com/dortania/OpenCore-Legacy-Patcher/tree/sequoia-development/payloads/Kexts/Acidanthera)

**Comment by perez987** [comment] 2024-08-01 18:19
@txl263 
About `Unsupported Host OS` I don't have more ideas, it's something I never got.
Get a newer copy of OCLP in case devs do any improvement to fix your issue.

**Comment by perez987** [comment] 2024-08-01 20:42
@txl263 
A friend of mine has the unsupported host issue with some of the nightly builds but [this](https://github.com/dortania/OpenCore-Legacy-Patcher/actions/runs/9783955206) works fine (for him).

**Comment by txl263** [comment] 2024-08-04 09:43
@perez987 
WiFi is back！
![image](https://github.com/user-attachments/assets/ed53f1c0-8d3a-4c38-bc94-b1b616c7ee19)
Iphone Mirroring still down. Is that needs something else or just can't run right now?
![image](https://github.com/user-attachments/assets/7daeac47-19e3-4a3c-848e-edc19ea9d923)

**Comment by perez987** [comment] 2024-08-04 12:44
@txl263 
Glad to read you!

iPhone Mirroring is something that the requirements for it to work are still not very clear.
In the European Community, for now, it will not work.
I think it requires iOS 18 beta (previous versions do not work) and both devices connected to the same Wi-Fi network.
But there are those who think that it will only work on Silicon Macs and not on Intel Macs, I am not sure about this.
There are also requirements for the iPhone model, although I believe the 15 is supported.

**Comment by txl263** [comment] 2024-08-04 12:52
@perez987 
From the previous article, I thought there was no requirement for the chip... Nothing to look forward to, then

**Comment by maseair** [comment] 2024-09-23 14:57
I also got that "Unsupported Host OS" warning and I'm using OCLP 1.4.3 since it's the only working version for my Thinkpad T440p to use root patching for graphics acceleration (it will stuck on boot if using 1.5.0 or later, i know how to revert root patch from recoveryOS terminal and it works without graphics acceleration).
I selected one of the SMBIOS (I have tried 3 different SMBIOS) and this warning still persists.
Do I need to keep finding another SMBIOS? And can anyone help me with the stuck on boot issue?
Thanks.

**Comment by perez987** [comment] 2024-09-23 21:41
@maseair 
Your question is out of the scope of the repo but I'll try to help since @txl263 had the same issue.

Are you on Sequoia? If so, does OCLP root patch work fine on Sonoma?

This error is often fixed by re-downloading OCLP, completely uninstalling OCLP, restarting the PC and installing the newly downloaded OCLP. But it is not always fixed this way.

You have to re-download 1.4.3 as you say that is the only one that works.

About SMBIOS, I think that you must use the working one of the former macOS.

If this is not enough, I don't have much more help to offer.

**Comment by maseair** [comment] 2024-09-23 22:56
@perez987 Thanks a lot for your response! First I apologize for my question being out of scope of this repo.

Yes, Im currently using Sequoia, and the oclp root patch works with Sonoma. I will try to fix this issue with your suggestions and I’ll keep you updated.

**Comment by perez987** [comment] 2024-10-03 00:03
@maseair 
Closing for now, but despite this you can comment any interesting thing.

**Closed as completed by perez987** 2024-10-03 00:03 UTC
Labels: question
